"""
dashboard/streamlit_app.py
───────────────────────────
Fraud AI Investigator — Streamlit Dashboard

Week 1: Placeholder showing system status and raw dataset preview.
Full investigation workflow added in Week 6.

Run with:
    uv run streamlit run dashboard/streamlit_app.py
"""

import json
from pathlib import Path

import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Fraud AI Investigator",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.markdown("### 🔍 Fraud AI Investigator")
    st.markdown("**v0.1.0** — Week 1 Setup")
    st.divider()
    st.markdown("**Navigation**")
    page = st.radio(
        label="Page",
        options=["System Status", "Dataset Explorer", "About"],
        label_visibility="collapsed",
    )
    st.divider()
    st.markdown("**API**")
    st.markdown("[FastAPI Docs →](http://localhost:8000/docs)")
    st.caption("Make sure the API is running:\n`uvicorn app.main:app --reload`")


# ── Data loader ───────────────────────────────────────────────────────────────

DATA_DIR = Path(__file__).parent.parent / "app" / "data"


@st.cache_data
def load_transactions():
    path = DATA_DIR / "transactions.json"
    if not path.exists():
        return []
    with open(path) as f:
        return json.load(f)


@st.cache_data
def load_kyc_profiles():
    path = DATA_DIR / "kyc_profiles.json"
    if not path.exists():
        return []
    with open(path) as f:
        return json.load(f)


@st.cache_data
def load_sanctions():
    path = DATA_DIR / "sanctions_watchlist.json"
    if not path.exists():
        return []
    with open(path) as f:
        return json.load(f)


# ── Pages ─────────────────────────────────────────────────────────────────────

if page == "System Status":
    st.title("System Status")
    st.caption("Week 1 — Environment setup complete")

    transactions = load_transactions()
    profiles = load_kyc_profiles()
    sanctions = load_sanctions()

    data_ready = len(transactions) > 0

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Transactions", len(transactions))
    with col2:
        flagged = sum(1 for t in transactions if t.get("is_flagged"))
        st.metric("Flagged (synthetic)", flagged)
    with col3:
        st.metric("KYC Profiles", len(profiles))
    with col4:
        st.metric("Sanctions Entries", len(sanctions))

    st.divider()

    st.subheader("Component checklist")

    checks = {
        "✅ GitHub repo created": True,
        "✅ Python environment (uv)": True,
        "✅ Project folder structure": True,
        "✅ Pydantic data models": True,
        "✅ FastAPI health endpoint": True,
        "✅ Synthetic UAE dataset": data_ready,
        "✅ pytest test suite": True,
        "⏳ Alert engine (Week 2)": False,
        "⏳ Triage agent (Week 3–4)": False,
        "⏳ LangGraph multi-agent (Week 5–7)": False,
        "⏳ HITL review (Week 8–9)": False,
        "⏳ Full dashboard (Week 10–11)": False,
        "⏳ Hugging Face deployment (Week 12)": False,
    }

    done = sum(1 for v in checks.values() if v)
    st.progress(done / len(checks), text=f"{done}/{len(checks)} phases complete")

    for label, complete in checks.items():
        if complete:
            st.success(label)
        else:
            st.info(label)

elif page == "Dataset Explorer":
    st.title("Synthetic Dataset Explorer")
    st.caption("All data is synthetic — generated by scripts/generate_data.py")

    tab1, tab2, tab3 = st.tabs(["Transactions", "KYC Profiles", "Sanctions Watchlist"])

    with tab1:
        transactions = load_transactions()
        if not transactions:
            st.warning("No transactions found. Run: `uv run python scripts/generate_data.py`")
        else:
            flagged = [t for t in transactions if t.get("is_flagged")]
            normal = [t for t in transactions if not t.get("is_flagged")]

            col1, col2, col3 = st.columns(3)
            col1.metric("Total", len(transactions))
            col2.metric("Flagged (20%)", len(flagged), delta="suspicious")
            col3.metric("Normal (80%)", len(normal))

            st.subheader("All transactions")
            filter_flagged = st.checkbox("Show flagged only")
            data = flagged if filter_flagged else transactions
            st.dataframe(data, use_container_width=True)

    with tab2:
        profiles = load_kyc_profiles()
        if not profiles:
            st.warning("No KYC profiles found. Run: `uv run python scripts/generate_data.py`")
        else:
            mismatches = [p for p in profiles if p.get("has_device_mismatch")]
            col1, col2 = st.columns(2)
            col1.metric("Total profiles", len(profiles))
            col2.metric("Device mismatches", len(mismatches))
            st.dataframe(profiles, use_container_width=True)

    with tab3:
        sanctions = load_sanctions()
        if not sanctions:
            st.warning("No sanctions data. Run: `uv run python scripts/generate_data.py`")
        else:
            st.metric("Watchlist entries", len(sanctions))
            for entry in sanctions:
                with st.expander(f"🚫 {entry['name']} ({entry['country']})"):
                    st.write(f"**Reason:** {entry['reason']}")
                    st.write(f"**Date listed:** {entry['date_listed']}")
                    if entry.get("aliases"):
                        st.write(f"**Aliases:** {', '.join(entry['aliases'])}")

elif page == "About":
    st.title("About this project")

    st.markdown("""
    ## Fraud AI Investigator

    An agentic AI system for end-to-end financial fraud analysis,
    built as a portfolio project for a fintech career in the UAE/MENA region.

    ### What this demonstrates
    - **Multi-agent orchestration** using LangGraph
    - **Explainable AI** — every risk score has a narrative
    - **Human-in-the-loop governance** — analysts review high-risk cases
    - **Regulatory awareness** — UAE CBUAE thresholds, FATF corridors
    - **Production architecture** — FastAPI + Pydantic + Docker + CI/CD

    ### Tech stack
    | Component | Technology |
    |---|---|
    | API backend | FastAPI + Pydantic v2 |
    | Agent workflow | LangGraph |
    | Primary LLM | Gemini 2.5 Flash (free) |
    | Fallback LLM | Groq / Llama 3 (free) |
    | Dashboard | This Streamlit app |
    | Hosting | Hugging Face Spaces (free) |

    ### Target companies
    This project is designed to showcase skills relevant to:
    - **Adyen** — payment processing and fraud systems
    - **Stripe** — ML-based fraud scoring
    - **Checkout.com** — UAE/MENA payment corridors
    - **Uber Payments** — real-time fraud analytics

    ### Cost
    **$0/month** — all free tier APIs and hosting.
    """)
